plugin:
  folder: ./agwPluginsAndLogsFolder/plugins
spring:
  application:
    name: autumn-gateway
  profiles:
    active: test
  redis:
    host: 10.133.92.157
    password: redis@2021
    database: 7


