spring:
  application:
    name: autumn-gateway
  profiles:
    active: test
  data:
    redis:
      host: qkp-dev-mc6-mw.qm.cn
      port: 33000
      password: devApinewredis@2022
      database: 7
autumn:
  server:
    bodyLimit: 150
    port: 80
    instances: 16
  zookeeper:
    cluster-Config:
      zookeeperHosts: qkp-dev-mc6-mw.qm.cn:32202
      root-path: autumn.vertx
      retry:
        initialSleepTime: 3000
        maxTimes: 3
    sync-path: /autumn/gateway/sync
plugin:
  folder: /Users/qiushi/ideaProject/autumn-gateway/plugins




