plugin:
  folder: ./plugins
spring:
  application:
    name: autumn-gateway
  profiles:
    active: test
  redis:
    host: 10.133.92.157
    password: redis@2021
    database: 7
autumn:
  server:
    bodyLimit: 150
    port: 80
    instances: 16
  zookeeper:
    cluster-Config:
      zookeeperHosts: dev-fc2mw-agw-agwcore-zookeeper.qm.cn:32202
      root-path: autumn.vertx
      retry:
        initialSleepTime: 3000
        maxTimes: 3
    sync-path: /autumn/gateway/sync


